server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
